config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here

  resources :user_emails do
    member do
      get :mark_primary
      get :resend_confirmation
      get :confirm
    end
  end

  namespace :admin do
    resources :users do
      resources :user_emails
    end
  end

end

app/models/spree/user_decorator.rb
Spree.user_class.class_eval do

  # Associations
  has_many :emails, class_name: "Spree::UserEmail", dependent: :destroy, foreign_key: :user_id
  has_one :primary_email, -> { primary },
                          class_name: "Spree::UserEmail",
                          foreign_key: :user_id,
                          dependent: :destroy

  # Validations
  validates :primary_email, presence: true

  # Callbacks
  before_validation :set_primary_email, on: :create
  after_update :update_primary_email, if: :email_changed?
  after_update :set_primary_email_confirmation, if: [:confirmed_at_changed?, :confirmed?]

  alias_method :user_emails, :emails

  private

    def set_primary_email
      build_primary_email email: email
    end

    def update_primary_email
      primary_email.update(email: email)
    end

    def set_primary_email_confirmation
      primary_email.update(confirmed_at: Time.current)
    end

end

app/models/spree/user_email.rb
module Spree
  class UserEmail < Spree::Base

    # Associations
    belongs_to :user, class_name: Spree.user_class.to_s

    # Validations
    validates :user, :email, presence: true
    validates :email, email: true
    validates :email, uniqueness: { scope: :user }, allow_blank: true

    # Callbacks
    before_validation :set_confirmation_token, on: :create, if: :confirmable?
    after_update :update_user_email, if: [:primary_changed?, :primary?]
    after_commit :send_confirmation_instructions, on: :create, if: :confirmable?

    # Scopes
    scope :primary, -> { where(primary: true) }

    def mark_primary
      if primary_markable?
        user.primary_email.update(primary: false)
        self.update(primary: true)
      end
    end

    def send_confirmation_instructions
      unless primary?
        Spree::UserEmailMailer.confirmation_instructions(self).deliver_later
      end
    end

    def confirm
      update(confirmed_at: Time.current)
    end

    def confirmed?
      confirmed_at.present?
    end

    def primary_markable?
      !confirmable? || (confirmable? && confirmed?)
    end

    private

      def confirmable?
        Spree::Auth::Config[:confirmable]
      end

      def update_user_email
        # Now all the user related operations will happen through this email including login.
        user.update(email: email, login: email)
      end

      def set_confirmation_token
        self.confirmation_token = Devise.friendly_token
      end

  end
end

app/controllers/spree/admin/user_emails_controller.rb
module Spree
  module Admin
    class UserEmailsController < ResourceController

      belongs_to 'spree/user', find_by: :id

    end
  end
end

app/controllers/spree/user_emails_controller.rb
module Spree
  class UserEmailsController < Spree::BaseController

    before_action :set_user
    before_action :set_user_email, only: [:edit, :update, :destroy, :mark_primary, :resend_confirmation, :confirm]

    def new
      @user_email = @user.emails.build(email: nil)
    end

    def create
      @user_email = @user.emails.build user_email_permitted_attributes
      if @user_email.save
        flash[:success] = t(".success")
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @user_email.update(user_email_permitted_attributes)
        flash[:success] = t(".success")
      else
        render :edit
      end
    end

    def destroy
      if @user_email.destroy
        flash[:success] = t(".success")
      else
        flash[:error] = t(".error")
      end
    end

    def mark_primary
      @user_email.mark_primary
      if @user_email.primary?
        flash[:success] = t(".success", email: @user_email.email)
      else
        flash[:error] = t(".error", email: @user_email.email)
      end
    end

    def resend_confirmation
      @user_email.send_confirmation_instructions
      flash[:success] = t(".success", email: @user_email.email)
    end

    def confirm
      @user_email.confirm if params[:confirmation_token] == @user_email.confirmation_token
      if @user_email.confirmed?
        flash[:success] = t(".success", email: @user_email.email)
        redirect_to account_path(@user_email.user)
      else
        flash[:error] = t(".success", email: @user_email.email)
        redirect_to account_path(@user_email.user)
      end
    end

    private

      def user_email_permitted_attributes
        params.require(:user_email).permit(:email)
      end

      def set_user
        @user = Spree.user_class.find_by(id: params[:user_id]) || spree_current_user
      end

      def set_user_email
        @user_email = Spree::UserEmail.find_by(id: params[:id])
      end

  end
end

app/controllers/spree/users_controller_decorator.rb
Spree::UsersController.class_eval do

  before_action :assign_user_emails, only: :show

  private

    def assign_user_emails
      @user_emails = @user.emails
    end

end

app/views/spree/admin/user_emails/_form.html.erb
<div>
  <%= f.field_container :email, class: ["form-group"] do %>
    <%= f.label :email, class: "form-title" %><br>
    <%= f.email_field :email, class: "form-control" %>
    <%= f.error_message_on :email %>
  <% end %>
</div>

app/views/spree/admin/user_emails/edit.html.erb
<% content_for :page_title do %>
  <%= link_to @user.email, edit_admin_user_url(@user) %> / <%= Spree.t(:edit_user_email) %> / <%= @user_email.email %>
<% end %>

<%= render partial: 'spree/admin/users/sidebar', locals: { current: :emails } %>
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @user_email } %>

<%= form_for [:admin, @user, @user_email] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/user_emails/index.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:users), admin_users_path %> / <%= link_to @user.email, edit_admin_user_url(@user) %> / Emails
<% end %>

<%= render partial: 'spree/admin/users/sidebar', locals: { current: :emails } %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_user_email), new_object_url, icon: 'add', class: 'btn-success' %>
<% end %>

<% if @user_emails.present? %>
  <table class="table">
    <thead>
      <th><%= Spree.t(:email) %></th>
      <% if Spree::Auth::Config[:confirmable] %>
        <th><%= Spree.t(:verified) %></th>
      <% end %>
      <th></th>
    </thead>
    <tbody>
      <% @user_emails.each do |user_email| %>
        <tr>
          <td><%= user_email.email %> <span class="label label-success"><%= Spree.t(:primary) if user_email.primary? %></span></td>
          <% if Spree::Auth::Config[:confirmable] %>
            <td><%= user_email.confirmed? %></td>
          <% end %>
          <td class="actions actions-2 text-right">
            <%= link_to_edit user_email, no_text: true if can? :edit, user_email %>
            <%= link_to_delete user_email, no_text: true if can? :destroy, user_email %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::UserEmail)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

app/views/spree/admin/user_emails/new.html.erb
<% content_for :page_title do %>
  <%= link_to @user.email, edit_admin_user_url(@user) %> / <%= Spree.t(:new_user_email) %>
<% end %>

<%= render partial: 'spree/admin/users/sidebar', locals: { current: :emails } %>
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @user_email } %>

<%= form_for [:admin, @user, @user_email], url: collection_url do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/users/_user_emails_tab.html.erb
<li<%== ' class="active"' if current == :emails %>>
  <%= link_to_with_icon 'envelope', Spree.t(:"admin.user.emails"), spree.admin_user_user_emails_path(@user) %>
</li>

app/views/spree/shared/_flash_message.js.erb
<% if flash[:success].present? %>
  show_flash("success", "<%= flash.discard(:success) %>")
<% elsif flash[:error].present? %>
  show_flash("error", "<%= flash.discard(:error) %>")
<% end %>

app/views/spree/user_emails/_form.html.erb
<%= form_for @user_email, remote: true do |f| %>
  <div>
    <%= f.field_container :email, class: ["form-group"] do %>
      <%= f.label :email, class: "form-title" %><br>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.error_message_on :email %>
    <% end %>
  </div>
  <%= f.submit nil, class: "btn btn-success" %>
<% end %>

app/views/spree/user_emails/_user_email.html.erb
<tr data-id=<%= user_email.id %>>
  <td class="text-left" data-hook="email_content"><%= user_email.email %></td>
  <td class="text-center">
    <% if user_email.primary? %>
      <span class="label label-success"><%= Spree.t(:primary) %></span>
    <% elsif user_email.primary_markable? %>
      <%= link_to Spree.t(:mark_primary), mark_primary_user_email_path(user_email), remote: true, class: "btn btn-xs btn-default" %>
    <% else %>
      <%= Spree.t(:please_verify_first) %>
    <% end %>
  </td>
  <% if Spree::Auth::Config[:confirmable] %>
    <td class="text-center">
      <% if user_email.confirmed? %>
        <%= Spree.t(:verified) %>
      <% else %>
        <%= Spree.t(:Unverified) %>. <%= link_to Spree.t(:resend), resend_confirmation_user_email_path(user_email), remote: true %>
      <% end %>
    </td>
  <% end %>
  <td class="text-center">
    <%= link_to Spree.t(:edit), edit_user_email_path(user_email), data: { remote: true }, class: "btn btn-xs btn-default" if can? :edit, user_email  %>
    <%= link_to Spree.t(:remove), user_email, method: :delete, data: { remote: true }, class: "btn btn-xs btn-danger" if can? :destroy, user_email %>
  </td>
</tr>

app/views/spree/user_emails/create.js.erb
$("[data-hook='user_email_form']").html("");
$('#user_emails').append('<%= j render @user_email %>');
<%= render partial: "spree/shared/flash_message" %>

app/views/spree/user_emails/destroy.js.erb
<% if @user_email.destroyed? %>
  $("[data-id='<%= @user_email.id %>']").remove();
<% end %>
<%= render partial: "spree/shared/flash_message" %>

app/views/spree/user_emails/edit.js.erb
$("[data-hook='user_email_form']").html("<%= j render 'form' %>");

app/views/spree/user_emails/mark_primary.js.erb
<% if @user_email.primary? %>
  $("#user_emails").html("<%= j render @user_email.user.emails %>");
<% end %>
<%= render partial: "spree/shared/flash_message" %>

app/views/spree/user_emails/new.js.erb
$("[data-hook='user_email_form']").html("<%= j render 'form' %>");

app/views/spree/user_emails/resend_confirmation.js.erb
<%= render partial: "spree/shared/flash_message" %>

app/views/spree/user_emails/update.js.erb
$("[data-id='<%= @user_email.id %>']").find("[data-hook='email_content']").html('<%= j @user_email.email %>');
$("[data-hook='user_email_form']").html("");
<%= render partial: "spree/shared/flash_message" %>

app/views/spree/users/_my_emails.html.erb
<div data-hook="account_my_emails">
  <h3><%= Spree.t(:my_emails) %></h3>
  <% if @my_emails.present? %>
    <table class="table table-striped my_emails">
      <thead class="active">
      <tr>
        <th class="user_email"><%= Spree.t(:email) %></th>
        <th class="user_email_primary text-center"><%= Spree.t(:primary) %></th>
        <th class="user_email_actions"></th>
      </tr>
      </thead>
      <tbody id="user_emails">
        <%= render @my_emails %>
      </tbody>
    </table>
  <% else %>
    <div class="alert alert-info"><%= Spree.t(:you_have_no_emails_yet) %></div>
  <% end %>
  <div>
    <%= link_to "Add new email", new_user_email_path(user_id: @user.id), remote: true, class: "btn btn-primary" %>
  </div>
  <div data-hook="user_email_form"></div>
</div>

app/views/spree/users/_user_emails.html.erb
<div data-hook="account_user_emails">
  <h3><%= Spree.t(:my_emails) %></h3>
  <% if @user_emails.present? %>
    <table class="table table-striped user_emails">
      <thead class="active">
      <tr>
        <th class="user_email"><%= Spree.t(:email) %></th>
        <th class="user_email_primary text-center"><%= Spree.t(:primary) %></th>
        <% if Spree::Auth::Config[:confirmable] %>
          <th class="user_email_primary text-center"><%= Spree.t(:verified) %></th>
        <% end %>
        <th class="user_email_actions"></th>
      </tr>
      </thead>
      <tbody id="user_emails">
        <%= render @user_emails %>
      </tbody>
    </table>
  <% else %>
    <div class="alert alert-info"><%= Spree.t(:you_have_no_emails_yet) %></div>
  <% end %>
  <div>
    <%= link_to "Add new email", new_user_email_path(user_id: @user.id), remote: true, class: "btn btn-primary" %>
  </div>
  <div data-hook="user_email_form"></div>
</div>